id: P8AA34A63
initial_creation_type: input
source_metadata:
  title: Tulku Zangpo Drakpa
  language: bo
  description: 'Texts revealed by the 14th-century tertön Zangpo Drakpa (bzang po
    grags pa):'
  volume:
    e444167daeb046e797885c28831a3b4e:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    a75ceaf5a31e4518a14e96ce2b558aa6:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    b0c1d92e8c8a425e8edb87ac664962e7:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    eab4caf3a6ac417f976438efb43b9ef7:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    fb8487524a2e455aae420f62cc60f455:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    77e7b363467d43d3bd187dc308061075:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    f970090a71364c55921209f14b17dacb:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    b1a7bf7e4e3d4cbebbd8fdac9c8ce138:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
created_at: '2022-03-01T01:59:25.931045'
last_modified_at: '2022-03-01T01:59:25.931048'
